### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by gadLinux** [rlink-rs/rlink-rs#68]
Hello, 

Is it usable? What's the current status?
It would be nice to have a roadmap and status in the README.md. Could you add it?

**Comment by BoredTape** [comment]
i want to know too

**Comment by yorkart** [comment]
I'm sorry that I couldn't reply in time. Due to heavy overtime, I couldn't concentrate on the project.
In the past 22 years, my personal work has changed a lot and I mainly focus on time sequence storage, so my time investment in this project has weakened (overtime work is very serious). Of course, I am also thinking about whether to continue to do independent and complete stream computing or to integrate them, such as the direction of stream database.

**Comment by gadLinux** [comment]
There are very good alternatives on streams sql engines like Arroyo. But I'm more interested in a streaming platform like KSttreams from confluent that can run independent composable ms. I'm understand.
